# agents/crop_agent_invocation.py

import logging
from typing import AsyncGenerator

# Placeholder for functions that would fetch real-time or user-specific data.
# In a real app, these would query databases, external APIs, etc.
def _fetch_location_data(user_id: str) -> str:
    """Placeholder to fetch farmer's location."""
    logging.info(f"Fetching location for user {user_id}...")
    return "Kharagpur, West Bengal"

def _fetch_crop_data(user_id: str) -> str:
    """Placeholder to fetch farmer's current crop."""
    logging.info(f"Fetching crop for user {user_id}...")
    return "Rice (Swarna-Sub1)"

def _fetch_weather_data(location: str) -> str:
    """Placeholder for a weather API call."""
    logging.info(f"Fetching weather for {location}...")
    return "Partly cloudy, 32°C, 85% humidity. Forecast: Light rain in the next 48 hours."

async def invoke_crop_agent_chain(
    rag_chain,
    ensemble_retriever,
    query: str,
    user_id: str = "user_123" # Example user ID
) -> AsyncGenerator[str, None]:
    """
    Gathers all necessary context and invokes the Crop RAG chain to get a streamed response.

    Args:
        rag_chain: The initialized, runnable RAG chain for the Crop Agent.
        ensemble_retriever: The retriever for fetching context documents.
        query (str): The user's question.
        user_id (str): The ID of the user to fetch personalized context.

    Yields:
        str: Chunks of the response as they are generated by the LLM.
    """
    logging.info(f"Crop Agent invoked for query: '{query}'")

    # 1. Gather all contextual information
    location = _fetch_location_data(user_id)
    crop_name = _fetch_crop_data(user_id)
    weather = _fetch_weather_data(location)

    # 2. Retrieve relevant documents from the vector store
    # This context will be fed directly into the prompt.
    retrieved_docs = ensemble_retriever.invoke(query)
    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)
    context_str = format_docs(retrieved_docs)

    # 3. Construct the input object for the RAG chain
    # This must match the variables in the updated RAG chain prompt.
    chain_input = {
        "query": query,
        "location": location,
        "crop_name": crop_name,
        "weather": weather,
        "context": context_str
    }

    # 4. Stream the response from the RAG chain
    async for chunk in rag_chain.astream(chain_input):
        yield chunk

    logging.info("Crop Agent streaming finished.")